#!/bin/bash

# Change permissions on the certificate.
# bitnami requires that the certificate permissions not be open.
chmod 400 bitnami-hosting.cer

# Forward requests from the localhost to the bitnami server.
# Don't check that the host is recognized; it's too hard to say yes or no.
# Make sure to run this process in the background.
ssh -N -L 3307:127.0.0.1:3306 -i ./bitnami-hosting.cer -o "StrictHostKeyChecking no" ubuntu@54.148.183.206 &
